services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ficha_web
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@demo.local
      DJANGO_SUPERUSER_PASSWORD: admin12345
      DEBUG: "true"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
      - media:/app/media
      - static:/app/staticfiles
    command: >
        sh -c "python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
volumes:
  media:
  static: